name: Luma_Job CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-test:
    name: 'Run tests'
    
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Luma_Job Run tests with Maven
      run: mvn test -e

    - name: Create test report
      uses: dorny/test-reporter@v1.8.0
      if: success() || failure()
      with:
        name: Test Execution Report
        path: target/surefire-reports/TEST-*.xml
        reporter: java-junit  
        
